; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=aggressive-instcombine -S | FileCheck %s
; XFAIL: *
;
; DEMONSTRATION TEST (ravn/llvm-z80#165) — expected to FAIL on current upstream;
; the CHECK lines assert the POST-FIX behavior.  Remove the `XFAIL` line once
; the TruncInstCombine outside-user extension lands.
;
; TruncInstCombine's outside-graph user allowlist only admitted `icmp <pred> X,
; Const`.  A narrowable expression whose in-graph value ALSO feeds (a) an icmp
; against a *non-constant* but provably-narrow operand, or (b) an `(and X,
; Const)` where Const fits the narrow type, was left at the wide type.  The fix
; admits both, rewriting the outside user so downstream consumers keep their
; original width.  Without the fix the `add` below stays i32; with it, it
; narrows to i16.

; (a) icmp with a non-constant, KnownBits-narrow other operand.
define i16 @icmp_nonconst_outside_user(i32 %x, i32 %y) {
; CHECK-LABEL: define i16 @icmp_nonconst_outside_user(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = trunc i32 [[X]] to i16
; CHECK-NEXT:    [[ADD:%.*]] = add i16 [[TMP1]], 1
; CHECK-NEXT:    [[YM:%.*]] = and i32 [[Y]], 255
; CHECK-NEXT:    [[TMP2:%.*]] = trunc i32 [[YM]] to i16
; CHECK-NEXT:    [[C:%.*]] = icmp ult i16 [[ADD]], [[TMP2]]
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[C]], i16 [[ADD]], i16 0
; CHECK-NEXT:    ret i16 [[SEL]]
;
  %add = add i32 %x, 1
  %t = trunc i32 %add to i16
  %ym = and i32 %y, 255
  %c = icmp ult i32 %add, %ym
  %sel = select i1 %c, i16 %t, i16 0
  ret i16 %sel
}

; (b) (and X, Const) outside-graph user, Const fits the narrow type.
define i16 @and_mask_outside_user(i32 %x) {
; CHECK-LABEL: define i16 @and_mask_outside_user(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = trunc i32 [[X]] to i16
; CHECK-NEXT:    [[ADD:%.*]] = add i16 [[TMP1]], 1
; CHECK-NEXT:    [[AND:%.*]] = and i16 [[ADD]], 15
; CHECK-NEXT:    [[TMP2:%.*]] = zext i16 [[AND]] to i32
; CHECK-NEXT:    store i32 [[TMP2]], ptr @g, align 4
; CHECK-NEXT:    ret i16 [[ADD]]
;
  %add = add i32 %x, 1
  %t = trunc i32 %add to i16
  %and = and i32 %add, 15
  store i32 %and, ptr @g
  ret i16 %t
}
@g = global i32 0
